---
- name: Run cfgUpdate
  hosts: " {{ selected_group }} "
  gather_facts: no
  tasks:
    - name: Execute cfgUpdate.exe
      win_command: '"C:\\Program Files (x86)\\ManageEngine\\UEMS_Agent\\bin\\cfgUpdate.exe"'

