---
- name: Example Playbook
  hosts: localhost
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    
  tasks:
    
    - name: Debug to verify credentials
      debug:
        msg:
          - "Selected Credential: {{ selected_credential }}"
          - "Resolved User: {{ ansible_user }}"
          - "Resolved Password: {{ '******' if ansible_password else 'Not Set' }}"

    - name: Get hostname
      win_shell: hostname
      register: hostname_result

    - name: Show hostname
      debug:
        var: hostname_result.stdout
