---
- name: dcconfig refresh
  hosts: " {{ selected_group }} "
  become: yes
  tasks:
    - name: Run dcconfig refresh
      command: sudo ./dcconfig refresh
      args:
        chdir: /usr/local/manageengine/uems_agent/bin/

