
- name: Gather system info and export to SMB share using CIFS
  hosts: "{{ selected_group }}"
  become: yes
  gather_facts: false

  vars:

  tasks:
    - name: Get running services
      shell: systemctl list-units --type=service --state=running
      register: running_services

    - name: Get disk space usage
      shell: df -h
      register: disk_usage

    - name: Get YUM history
      shell: yum list installed
      register: yum_list_installed
      
    - name: Get Dnf history
      shell: dnf history
      register: dnf_history
