- name: Gather system info and export to SMB share using smbclient
  hosts: "{{ selected_host }}"
  become: yes
  gather_facts: false

  tasks:
    - name: Get running services
      shell: systemctl list-units --type=service --state=running
      register: running_services

    - name: Get disk space usage
      shell: df -h
      register: disk_usage

    - name: Combine output
      set_fact:
        combined_output: |
          Running Services:
          {{ running_services.stdout }}

          Disk Usage:
          {{ disk_usage.stdout }}

    - name: Save output to local file on control node
      delegate_to: localhost
      copy:
        content: "{{ combined_output }}"
        dest: "/tmp/running_services_{{ inventory_hostname }}.txt"

    - name: Install smbclient on control node
      delegate_to: localhost
      become: true
      package:
        name: smbclient
        state: present

    - name: Upload file to SMB share using smbclient
      delegate_to: localhost
      become: false
      shell: >
        smbclient //172.16.17.40/Patch -U "administrator@dev.local%P@ssw0rd" -c "put /tmp/running_services_{{ inventory_hostname }}.txt"
