---
- name: Change local user password via survey
  hosts: "{{ selected_group }}"
  become: yes
  vars:
    username: "{{ survey_username }}"
    new_password: "{{ survey_password }}"

  tasks:
    - name: Hash the password
      ansible.builtin.set_fact:
        hashed_password: "{{ new_password | password_hash('sha512') }}"

    - name: Update user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ hashed_password }}"
