---
- name: Change local user password on Windows
  hosts: "{{ selected_group }}"
  vars:
    username: "{{ survey_username }}"
    new_password: "{{ survey_password }}"
  tasks:
    - name: Change password for local user
      ansible.windows.win_user:
        name: "{{ username }}"
        password: "{{ new_password }}"
        update_password: always
