- name: Install UEMSAgent
  hosts: all
  gather_facts: no
  collections:
    - ansible.windows

  vars:
    install_dir: C:\TEMP\UEMSAgent\WindowsAgent
    local_repo_path: /tmp/WindowsAgent
    repo_url: "https://{{ git_username }}:{{ git_token }}@gitlab.as1nfra.com/asker.chan/ansible.git"
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"

  tasks:
    - name: Create installation directory on Windows
      win_file:
        path: "{{ install_dir }}"
        state: directory



    - name: Install UEMSAgent using msiexec
      win_command: "{{ install_dir }}\\Autoinstall.bat"




