- name: Install UEMS Linux Agent
  hosts: all
  become: Yes
  become_method: sudo
  become_pass: P@33w0rd

  vars:
    repo_url: "https://github.com/askerchanASL/ansible.git"
    repo_dest: "/tmp/ME"

  tasks:
    - name: Clone UEMS Linux Agent from Git
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "main"
        force: yes


    - name: Make UEMS_LinuxAgent.bin executable
      ansible.builtin.file:
        path: "{{ repo_dest }}/LinuxAgent/UEMS_LinuxAgent.bin"
        mode: '0755'

    - name: Run the installer
      ansible.builtin.command:
        cmd: sudo ./UEMS_LinuxAgent.bin --silent
        chdir: "{{ repo_dest }}/LinuxAgent/"
      become: yes
    

    - name: Remove Folder
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: absent
      become: yes
