- name: Clone only LinuxAgent directory on AAP server
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    repo_url: "https://{{git_username}}:{{git_password}}@gitlab.as1nfra.com/asker.chan/ansible.git"
    repo_dest: "/tmp/ME"
    sparse_dir: "LinuxAgent"


- name: Install UEMS Linux Agent on target machines
  hosts: "{{ selected_group | default('all') }}"  
  become: true
  vars:
    repo_dest: "/tmp/ME"
    ansibe_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_become_password: "{{ ansible_password }}"

  tasks:


    - name: Make UEMS_LinuxAgent.bin executable
      ansible.builtin.file:
        path: "{{ repo_dest }}/AutoInstall.sh"
        mode: '0755'

    - name: Run the installer
      ansible.builtin.command:
        cmd: "./AutoInstall.sh"
        chdir: "{{ repo_dest }}"


