- name: Clone only LinuxAgent directory on AAP server
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    repo_url: "https://{{git_username}}:{{git_password}}@gitlab.as1nfra.com/askerchan/ansible.git"
    repo_dest: "/tmp/ME"
    sparse_dir: "LinuxAgent"

  pre_tasks:
    - name: Load GitLab credentials from vault
      delegate_to: localhost
      run_once: true
      ansible.builtin.include_vars:
        file: vault.yml


  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: directory

    - name: Initialize empty Git repo
      ansible.builtin.command:
        cmd: "git init"
        chdir: "{{ repo_dest }}"

    - name: Set remote origin
      ansible.builtin.command:
        cmd: "git remote add origin {{ repo_url }}"
        chdir: "{{ repo_dest }}"

    - name: Enable sparse checkout
      ansible.builtin.command:
        cmd: "git config core.sparseCheckout true"
        chdir: "{{ repo_dest }}"

    - name: Define sparse-checkout paths
      ansible.builtin.copy:
        dest: "{{ repo_dest }}/.git/info/sparse-checkout"
        content: |
          {{ sparse_dir }}

    - name: Pull only the specified directory
      ansible.builtin.command:
        cmd: "git pull origin main"
        chdir: "{{ repo_dest }}"


- name: Install UEMS Linux Agent on target machines
  hosts: "{{ selected_group | default('all') }}"  
  become: true
  vars:
    repo_dest: "/tmp/ME"
    ansibe_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_become_password: "{{ ansible_password }}"

  tasks:


    - name: Make UEMS_LinuxAgent.bin executable
      ansible.builtin.file:
        path: "{{ repo_dest }}/AutoInstall.sh"
        mode: '0755'

    - name: Run the installer
      ansible.builtin.command:
        cmd: "./AutoInstall.sh"
        chdir: "{{ repo_dest }}"


