- name: Install UEMS Linux Agent
  hosts: all
  vars:
    repo_url: "https://github.com/askerchanASL/ansible.git"
    repo_dest: "/tmp/ME"
      
  tasks:
    - name: Whoami
      ansible.builtin.command:
        cmd: whoami

    - name: Whoami Become
      ansible.builtin.command:
        cmd: whoami
      become: true
      
    - name: Clone UEMS Linux Agent from Git
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "main"
        force: yes

    - name: Make UEMS_LinuxAgent.bin executable
      ansible.builtin.file:
        path: "{{ repo_dest }}/LinuxAgent/UEMS_LinuxAgent.bin"
        mode: '0755'

    - name: Run the installer
      ansible.builtin.command:
        cmd: "./UEMS_LinuxAgent.bin"
        chdir: "{{ repo_dest }}/LinuxAgent/"
      become: true
      
    - name: Remove Folder
      ansible.builtin.file:
        path: "{{ repo_dest }}"
        state: absent
