---
- name: Take VMware VM snapshots
  hosts: localhost
  gather_facts: true
  collections:
    - community.vmware

  vars:
    # These are safe to define here
    vm_names:
      - "AskerChan_NATServer"
      - "AskerChan_Nomination"

    snapshot_name: "Take snapshot before patching {{ ansible_date_time.iso8601 }}"
    snapshot_description: "Snapshot taken before software patching"
    snapshot_memory: false
    snapshot_quiesce: false

  tasks:
    - name: Create snapshots for specified VMs
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ lookup('ee-minimal-rhel8-vmware', 'VMWARE_HOST' }}"
        username: "{{ lookup('ee-minimal-rhel8-vmware', 'VMWARE_USER' }}"
        password: "{{ lookup('ee-minimal-rhel8-vmware', 'VMWARE_PASSWORD' }}"
        validate_certs: "{{ lookup('ee-minimal-rhel8-vmware', VMWARE_VALIDATE_CERTS | default(false) }}"
        datacenter: "DC1"
        folder: "/"
        name: "{{ item }}"
        state: "present"
        snapshot_name: "{{ snapshot_name }}"
        description: "{{ snapshot_description }}"
        memory_dump: "{{ snapshot_memory }}"
        quiesce: "{{ snapshot_quiesce }}"
      loop: "{{ vm_names }}"
      register: snapshot_results
      ignore_errors: yes

    - name: Display snapshot results
      debug:
        var: snapshot_results.results
